services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    container_name: todo-server
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=todo
    - DB_USER=postgres
    - DB_PASSWORD=root
    - PORT=5000
    volumes:
    - ./server:/usr/src/app
    - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
    - "5173:5173"
    container_name: todo-client
    volumes:
    - ./client:/usr/src/app
    - /usr/src/app/node_modules 
volumes:
  postgres_data: